### PR TITLE
Update dotnet  from 6.0 to 8.0

### PR DESCRIPTION
**Pull request by popalex**
Update dotnet version from 6.0 to 8.0, latest LTS version at this time.

Signed-off-by: Alex Popescu <pop.alx@gmail.com>

### CODE REVIEW

**Review by ibuziuk — COMMENTED** [review]
@popalex thanks for the contribution, could you please sign off the commit - https://github.com/devfile/developer-images/pull/171/checks?check_run_id=24622985445
@svor are we good to bump the .net version?

**Comment by popalex** [comment]
> @popalex thanks for the contribution, could you please sign off the commit - https://github.com/devfile/developer-images/pull/171/checks?check_run_id=24622985445

done.

**Comment by svor** [comment]
> @popalex thanks for the contribution, could you please sign off the commit - https://github.com/devfile/developer-images/pull/171/checks?check_run_id=24622985445 @svor are we good to bump the .net version?

@ibuziuk changes are good to me. Only the problem with image build: https://github.com/devfile/developer-images/actions/runs/8966779944/job/24670229942?pr=171, but I don't think it's related to the current changes

**Comment by ibuziuk** [comment]
@musienko-maxim could you please take a look at why the PR check is failing ?

**Comment by svor** [comment]
the build fails because of https://github.com/eclipse-che/che/issues/22957

**Comment by svor** [comment]
@popalex could you please rebase your PR to pick up the latest changes from main branch, they contain the fix of image build problem

**Comment by popalex** [comment]
> ebase your PR to pick up the latest changes from main branch

Done I think.

**Pull request merged**
