### PR TITLE
chore: update dotnet version to 6.0

### PR DESCRIPTION
**Pull request by svor**
Update dotnet version to 6.0

Related issues: https://github.com/eclipse/che/issues/22077, https://github.com/eclipse/che/issues/21978

### CODE REVIEW

**Comment by nickboldt** [comment]
Why not update to dotnet 7?

https://github.com/redhat-developer/devspaces-images/blob/devspaces-3-rhel-8/devspaces-udi/Dockerfile#L251-L261

**Review by nickboldt — APPROVED** [review]
Why not update to dotnet 7?

https://github.com/redhat-developer/devspaces-images/blob/devspaces-3-rhel-8/devspaces-udi/Dockerfile#L251-L261

**Comment by svor** [comment]
[free-omnisharp-vscode](https://github.com/muhammadsammy/free-omnisharp-vscode) may work incorrectly with .NET 7. Let's start with .NET6 which is LTS

**Comment by nickboldt** [comment]
is that a different extension from what we use downstream?

**Pull request merged**
