### PR TITLE
chore: Remove docker since it is not supported

### PR DESCRIPTION
**Pull request by tolusha**
### Reference issue
https://github.com/eclipse/che/issues/22374

### CODE REVIEW

**Review by AObuchow — APPROVED** [review]

**Comment by AObuchow** [comment]
It might be worth squashing both commits together but LGTM

**Review by svor — APPROVED** [review]

**Comment by l0rd** [comment]
I would remove all the docker and compose section then.

**Comment by tolusha** [comment]
@l0rd Please approve changes

**Review by l0rd — APPROVED** [review]
LGTM 👏

**Review by svor — APPROVED** [review]

**Pull request merged**
